# -*- coding: utf-8 -*-
"""Inventory Management System

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oXLfqPbK-CQ7eIsWyegSw4z9benHmbNw
"""
!gdown 1xrlYu_eap-U9n5Vj585gHcpvvujQ8dyn


import json
import os
import pandas as pd
import matplotlib.pyplot as plt

class InventorySystem:
    class Item:
        def __init__(self, name, sku, quantity, price, supplier, threshold=0):
            self.name = name
            self.sku = sku
            self.quantity = quantity
            self.price = price
            self.supplier = supplier
            self.threshold = threshold

        def to_dict(self):
            return {
                "name": self.name,
                "sku": self.sku,
                "quantity": self.quantity,
                "price": self.price,
                "supplier": self.supplier,
                "threshold": self.threshold
            }

        @classmethod
        def from_dict(cls, data):
            return cls(data["name"], data["sku"], data["quantity"],
                       data["price"], data["supplier"], data["threshold"])

        def check_inventory(self):
            if self.quantity < self.threshold:
                self.alert()
            else:
                print(f"In Stock: {self.name} (SKU: {self.sku}) - Qty: {self.quantity}, Threshold: {self.threshold}")

        def alert(self):
            print(f"Alert: {self.name} (SKU: {self.sku}) - Qty: {self.quantity}, Threshold: {self.threshold}")

    def __init__(self, file_path="inventory.json", sales_file="sales.json", orders_file="orders.json", history_file="inventory_history.json"):  # CHANGE
        self.items = {}
        self.sales_report = []
        self.orders = []
        self.inventory_history = []
        self.file_path = file_path
        self.sales_file = sales_file
        self.orders_file = orders_file
        self.history_file = history_file
        self.load_from_file()
        self.load_sales_report()
        self.load_orders()
        self.load_inventory_history()

    def add_item(self, name, sku, quantity, price, supplier, threshold):
        if sku in self.items:
            print(f"Cannot add item: SKU {sku} already exists.")
            return
        item = self.Item(name, sku, quantity, price, supplier, threshold)
        self.items[sku] = item
        print(f"Added item: {name} (SKU: {sku})")

    def update_item(self, sku, quantity=None, price=None, supplier=None, threshold=None):
        if sku in self.items:
            item = self.items[sku]
            if quantity is not None:
                item.quantity = quantity
            if price is not None:
                item.price = price
            if supplier is not None:
                item.supplier = supplier
            if threshold is not None:
                item.threshold = threshold
            print(f"Updated item: {sku}")
        else:
            print("Item not found.")

    def delete_item(self, sku):
        if sku in self.items:
            del self.items[sku]
            print(f"Deleted item with SKU: {sku}")
        else:
            print("Item not found.")

    def display_inventory(self):
        if not self.items:
            print("Inventory is empty.")
        else:
            print("\nInventory List:")
            for item in self.items.values():
                print(f'Name: {item.name}, SKU: {item.sku}, Quantity: {item.quantity}, Price: ${item.price:.2f}, '
                      f'Supplier: {item.supplier}, Threshold: {item.threshold}')

    def search_item(self, search_criteria):
        results = []
        for item in self.items.values():
            if (search_criteria.lower() in item.name.lower() or
                search_criteria.lower() in item.sku.lower() or
                search_criteria.lower() in item.supplier.lower()):
                results.append(item)
        return results

    def filter_items(self, min_price=None, max_price=None, min_quantity=None):
        results = []
        for item in self.items.values():
            if (min_price is None or item.price >= min_price) and \
               (max_price is None or item.price <= max_price) and \
               (min_quantity is None or item.quantity >= min_quantity):
                results.append(item)
        return results

    def sell_item(self, sku, quantity):
        if sku in self.items and self.items[sku].quantity >= quantity:
            item = self.items[sku]
            total_price = round(item.price * quantity, 2)
            self.sales_report.append({
                "name": item.name,
                "sku": sku,
                "quantity": quantity,
                "total_price": total_price
            })
            item.quantity -= quantity
            print(f'Sold {quantity} of {item.name} for ${total_price:.2f}')
            item.check_inventory()
            self.record_inventory_snapshot()
        else:
            print('Insufficient stock or item not found.')

    def generate_sales_report(self):
        print("\nSales Report:")
        for record in self.sales_report:
            print(f'Item: {record["name"]}, SKU: {record["sku"]}, '
                  f'Quantity: {record["quantity"]}, Total: ${record["total_price"]:.2f}')
        if not self.sales_report:
            print("No sales recorded.")

    def re_order(self, sku, quantity):
        if sku in self.items:
            self.items[sku].quantity += quantity
            self.orders.append({
                "sku": sku,
                "quantity": quantity,
                "supplier": self.items[sku].supplier
            })
            print(f'Order recorded: {quantity} units of {sku}')
            self.items[sku].check_inventory()
            self.record_inventory_snapshot()
        else:
            print('Item not found in inventory.')

    def save_to_file(self):
        with open(self.file_path, 'w') as f:
            json.dump({sku: item.to_dict() for sku, item in self.items.items()}, f, indent=2)
        print("Inventory saved.")

    def load_from_file(self):
        if os.path.exists(self.file_path):
            with open(self.file_path, 'r') as f:
                data = json.load(f)
                for sku, item_data in data.items():
                    self.items[sku] = self.Item.from_dict(item_data)
            print("Inventory loaded.")

    def save_sales_report(self):
        with open(self.sales_file, 'w') as f:
            json.dump(self.sales_report, f, indent=2)

    def load_sales_report(self):
        if os.path.exists(self.sales_file):
            with open(self.sales_file, 'r') as f:
                self.sales_report = json.load(f)

    def save_orders(self):
        with open(self.orders_file, 'w') as f:
            json.dump(self.orders, f, indent=2)

    def load_orders(self):
        if os.path.exists(self.orders_file):
            with open(self.orders_file, 'r') as f:
                self.orders = json.load(f)

    def save_inventory_history(self):
        with open(self.history_file, 'w') as f:
            json.dump(self.inventory_history, f, indent=2)

    def load_inventory_history(self):
        if os.path.exists(self.history_file):
            with open(self.history_file, 'r') as f:
                self.inventory_history = json.load(f)

    def record_inventory_snapshot(self):
        snapshot = {
            "timestamp": pd.Timestamp.now().isoformat(),
            "inventory": {sku: item.quantity for sku, item in self.items.items()}
        }
        self.inventory_history.append(snapshot)

    def import_inventory_from_csv(self, csv_path):
        try:
            df = pd.read_csv(csv_path)
            for _, row in df.iterrows():
                self.add_item(
                    name=row['name'],
                    sku=row['sku'],
                    quantity=int(row['quantity']),
                    price=float(row['price']),
                    supplier=row['supplier'],
                    threshold=int(row.get('threshold', 0))
                )
            print(f"Imported inventory from {csv_path}")
        except Exception as e:
            print(f"Failed to import CSV: {e}")

    def export_inventory_to_csv(self, csv_path):
        try:
            data = [item.to_dict() for item in self.items.values()]
            df = pd.DataFrame(data)
            df.to_csv(csv_path, index=False)
            print(f"Inventory exported to {csv_path}")
        except Exception as e:
            print(f"Failed to export CSV: {e}")

    def visualize_inventory(self):
        if not self.inventory_history:
            print("No inventory history available.")
            return

        df = pd.DataFrame(self.inventory_history)
        df["timestamp"] = pd.to_datetime(df["timestamp"])
        df.set_index("timestamp", inplace=True)
        df_inventory = pd.json_normalize(df["inventory"])
        df_inventory.index = df.index

        timestamps = df_inventory.index.strftime("%Y-%m-%d %H:%M:%S")
        skus = df_inventory.columns
        x = range(len(timestamps))
        width = 0.8 / len(skus)

        plt.figure(figsize=(14, 6))
        for i, sku in enumerate(skus):
            plt.bar(
                [p + width * i for p in x],
                df_inventory[sku],
                width=width,
                label=sku
            )

        plt.title("Inventory Quantities Over Time (Bar Chart)")
        plt.xlabel("Timestamp")
        plt.ylabel("Quantity")
        plt.xticks([p + width for p in x], timestamps, rotation=45, ha='right')
        plt.legend(title="SKU", bbox_to_anchor=(1.05, 1), loc='upper left')
        plt.tight_layout()
        plt.show(block=False)
        plt.pause(1)
        plt.close()

    def exit_system(self):
        self.save_to_file()
        self.save_sales_report()
        self.save_orders()
        self.save_inventory_history()
        print("Goodbye!")

def main():
    system = InventorySystem()

    while True:
        print("\nInventory Menu:")
        print("1. Add Item")
        print("2. Sell Item")
        print("3. Re-Order")
        print("4. Display Inventory")
        print("5. Search Item")
        print("6. Sales Report")
        print("7. Delete Item")
        print("8. Save and Exit")
        print("9. Import Inventory from CSV")
        print("10. Export Inventory to CSV")
        print("11. Visualize Inventory Trends")

        choice = input("Enter choice: ")

        if choice == '1':
            name = input("Name: ")
            sku = input("SKU: ")
            quantity = int(input("Quantity: "))
            price = float(input("Price: "))
            supplier = input("Supplier: ")
            threshold = int(input("Threshold: "))
            system.add_item(name, sku, quantity, price, supplier, threshold)

        elif choice == '2':
            sku = input("SKU to sell: ")
            qty = int(input("Quantity to sell: "))
            system.sell_item(sku, qty)

        elif choice == '3':
            sku = input("SKU to order: ")
            qty = int(input("Quantity to order: "))
            system.re_order(sku, qty)

        elif choice == '4':
            system.display_inventory()

        elif choice == '5':
            keyword = input("Search keyword: ")
            results = system.search_item(keyword)
            if results:
                for item in results:
                    print(f"{item.name} - SKU: {item.sku}, Qty: {item.quantity}")
            else:
                print("No matching items found.")

        elif choice == '6':
            system.generate_sales_report()

        elif choice == '7':
            sku = input("Enter SKU of the item to delete: ")
            system.delete_item(sku)

        elif choice == '8':
            system.exit_system()
            break

        elif choice == '9':
            path = input("Enter CSV file path to import: ")
            system.import_inventory_from_csv(path)

        elif choice == '10':
            path = input("Enter CSV file path to export: ")
            system.export_inventory_to_csv(path)

        elif choice == '11':
            system.visualize_inventory()

        else:
            print("Invalid choice. Please try again.")

main()
